{
 "title": "ES Cluster Status",
 "description": "es 集群状态",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "ClusterName",
    "query": "label_values(es_cluster_status,env)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n\n<h2 style=\"background-color:green\">\n  <center>\n    <br>\n      生产环境ES集群状态\n    <br><br>\n  </center>\n</h2>\n\n\n\n\n"
   },
   "content": "\n\n<h2 style=\"background-color:green\">\n  <center>\n    <br>\n      生产环境ES集群: <span><strong>prodes</strong></span> 状态\n    <br><br>\n  </center>\n</h2>\n\n\n\n\n",
   "targets": [
    {
     "expr": "netdata_apps_cpu_percentage_average"
    }
   ]
  },
  { "title": "$cluster_name Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "cluster_name" },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "description": "**集群状态**\n\ngreen:  正常健康\n\nyellow:  代表分配了所有主分片,但至少缺少一个副本,此时集群数据仍旧完整\n\nred: 代表部分主分片不可用,可能已经丢失数据",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_cluster_status{env=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Node Total",
   "type": "singlestat",
   "description": "**集群总节点数**",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_node_total{env=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Data Node Total",
   "type": "singlestat",
   "description": "**集群数据节点数**",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_node_data{env=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "singlestat",
   "description": "**准备中的任务**\n\n如：复制等操作",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_pending_tasks{env=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Active Shards Percent",
   "type": "singlestat",
   "description": "**存活的分片百分比**",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_active_shards_percent{env=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "singlestat",
   "description": "**集群总分片数**",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_active_shards{env=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Active Master Shards",
   "type": "singlestat",
   "description": "**存活的主分片总数**",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_active_master_shards{env=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Max Task Wait Time",
   "type": "singlestat",
   "description": "**任务最长等待时间**\n\n",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_pending_tasks{env=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Eplo/Init/Unassign Shards",
   "type": "graph",
   "description": "**各状态分片数量**\n\neplo:  正在复制的分片数量\n\ninit:  正在初始化的分片数量\n\nunassign:  未分配的分片数量",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "es_relo_shards{env=\"$cluster_name\"}",
     "legendFormat": "relo"
    },
    {
     "expr": "es_init_shards{env=\"$cluster_name\"}",
     "legendFormat": "init"
    },
    {
     "expr": "es_unassign_shards{env=\"$cluster_name\"}",
     "legendFormat": "unassign"
    }
   ]
  }
 ]
}